### ISSUE TITLE
Não é possível criar uma conta como mentorado

### ISSUE THREAD

**Issue by ofelipedidio** [ofelipedidio/es-front-end#14]
Ao registrar um mentorado, a seguinte mensagem é apresentada:

![image](https://github.com/ofelipedidio/es-front-end/assets/36784465/6972bcbc-4e2e-4580-8c9d-75a92eca789b)

Dados inseridos no cadastro:

![image](https://github.com/ofelipedidio/es-front-end/assets/36784465/23552234-19d7-44a5-8fd6-2e208715c216)

Selecionando mentor, o campo que é falsamente requerido é apresentado:

![image](https://github.com/ofelipedidio/es-front-end/assets/36784465/f4d9943d-283d-4b78-98c5-c340e42cc39c)

**Comment by JoaoCosme** [comment]
Cara, aqui foi, pode testar com a ultima main?

**Comment by ofelipedidio** [comment]
Testei novamente e funcionou, obrigado @JoaoCosme.

**Comment by ofelipedidio** [comment]
Quando o usuário seleciona "Mentor" e volta para "Mentorado", o sistema assume que os campos de mentor ainda são obrigatórios.

Edit: eu vou resolver, re-abri para documentar.

**Comment by FelipeSchnitzler** [comment]
resolvido
